[project]
name = "azurebotservicenow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "agentic-kushtawar", email = "chandan.kushtawar@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.120.4",
    "loguru>=0.7.3",
    "uvicorn[standard]>=0.38.0",
]

[project.scripts]
azurebotservicenow = "azurebotservicenow:main"

[build-system]
requires = ["uv_build>=0.9.7,<0.10.0"]
build-backend = "uv_build"
